baseURL = 'https://qualitycluster.github.io'
languageCode = 'de-de'
paginate = 6
theme= "myCoHub"
title = 'QualityCLuster'
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Blog"
  url= "#blog"
  weight = 1
  [[menu.Main]]
  name = "Wer wir sind"
  url= "/about/"
  weight = 1
  [[menu.Main]]
  name = "Quality Manifesto"
  url= "#qualitymanifesto"
  weight = 1


  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  aboutPageURL = "werwirsind"
  contactLink = "contact"
  copyright = "© {year} qualityCluster."
  # formspreeURL = "https://formspree.io/mbjwlead"
  # googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/QualityCluster-logo.png"
  footerlogo = "images/QualityCluster-logo.png"
  footerDescription = "QualityCluster ist powered by Boiman.Solutions"

  [params.address]
  address = "Köln / Frankfurt"
  email = "info@qualitycluster.net"
  # openingDesc = "Give us a call or drop by anytime, we endeavour to answer all enquiries within 24 hours on business days."
  # openingHours = "We are open from 7am — 7pm week days."
  # phone = "+(448) 833 5272 332"

  [params.map]
  # APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  # 50.9295116,6.9595836,
   latitude = "50.9295116"
   longitude = "6.9595836"
   pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 3
  
  